version: '2'
services:
    jhipstersamplemsapplication2-app:
        image: jhipstersamplemsapplication2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersamplemsapplication2-mysql:3306/jhipstersamplemsapplication2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    jhipstersamplemsapplication2-mysql:
        extends:
            file: mysql.yml
            service: jhipstersamplemsapplication2-mysql
